name: Release
on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: 
      name: deploy
      url: https://mod.3dmgame.com/mod/174709
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest tag
        run: echo "tag=`git describe --tags`" >> $GITHUB_ENV
        shell: bash

      - name: Update information
        uses: ./
        id: update
        with:
          APPID: ${{ secrets.APPID }}
          APPKEY: ${{ secrets.APPKEY }}
          id: 174709
          version: ${{ env.tag }}
          content: README.md
          file: README.md

      - name: Print the response from the API
        run: "echo 'Code: ${{ steps.update.outputs.code }}\tMessage: ${{ steps.update.outputs.msg }}'"