name: Test
on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest tag
        run: echo "tag=`git describe --tags`" >> $GITHUB_ENV
        shell: bash

      - name: Test 1
        uses: ./
        id: test1
        with:
          APPID: 1234
          APPKEY: 1234
          id: 174709
          version: ${{ env.tag }}
          content: README.md
          file: README.md
          test: true

      - name: Print the response from Test 1
        run: "echo 'Code: ${{ steps.test1.outputs.code }}\tMessage: ${{ steps.test1.outputs.msg }}'"

      - name: Test 2
        uses: ./
        id: test2
        with:
          APPID: 1234
          APPKEY: 1234
          id: 174709
          file: dist/
          test: true

      - name: Print the response from Test 2
        run: "echo 'Code: ${{ steps.test2.outputs.code }}\tMessage: ${{ steps.test2.outputs.msg }}'"