name: Test
on:
  push:
    paths-ignore:
      - "README.md"
    branches-ignore:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest tag
        run: echo "tag=`git describe --tags`" >> $GITHUB_ENV
        shell: bash

      - name: Build
        run: |
          npm install
          npm run build

      - name: Test 1
        uses: ./
        id: test1
        with:
          APPID: 1234
          APPKEY: 1234
          id: 174709
          title: My Mod
          tags: mod, trainer, interface
          version: ${{ env.tag }}
          desc: my test mod
          content: README.md
          file: README.md
          test: true
      - name: Print the response from Test 1
        run: "echo 'Code: ${{ steps.test1.outputs.code }}\tMessage: ${{ steps.test1.outputs.msg }}'"

      - name: Test 2
        uses: ./
        id: test2
        with:
          APPID: 1234
          APPKEY: 1234
          id: 174709
          content: |
            # Introduction
            - It's a mod
            - It adds new weapons to the game.
          file: dist/
          zip-only: true
          test: true
      - name: Print the response from Test 2
        run: "echo 'Code: ${{ steps.test2.outputs.code }}\tMessage: ${{ steps.test2.outputs.msg }}\nFile: ${{ steps.test2.outputs.file }}'"

      - name: Test 3
        uses: ./
        id: test3
        with:
          APPID: 1234
          APPKEY: 1234
          id: 174709
          test: true
      - name: Print the response from Test 3
        run: "echo 'Code: ${{ steps.test3.outputs.code }}\tMessage: ${{ steps.test3.outputs.msg }}'"
