name: Update README
on: 
  push:
    branchees:
      - 'master'
    paths:
      - 'README.md'

jobs:
  update:
    runs-on: ubuntu-latest
    environment: 
      name: deploy
      url: https://mod.3dmgame.com/mod/174709
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README
        uses: ./
        id: update
        with:
          APPID: ${{ secrets.APPID }}
          APPKEY: ${{ secrets.APPKEY }}
          id: 174709
          content: README.md

      - name: Print the response from the API
        run: "echo 'Code: ${{ steps.update.outputs.code }}\tMessage: ${{ steps.update.outputs.msg }}'"